// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAds0SsUHnSQB0xH4iv0cTjlpfa7GtNx-Y',
    appId: '1:547078489764:web:6d0bc84d897c2dddf8c831',
    messagingSenderId: '547078489764',
    projectId: 'elsenwar1-94e9a',
    authDomain: 'elsenwar1-94e9a.firebaseapp.com',
    storageBucket: 'elsenwar1-94e9a.firebasestorage.app',
    measurementId: 'G-S3EH76GC2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUYLoVkRhWjyiF33_02Wp9RDnn5_Uk8iw',
    appId: '1:547078489764:android:c07f0c4cb25e5a4ef8c831',
    messagingSenderId: '547078489764',
    projectId: 'elsenwar1-94e9a',
    storageBucket: 'elsenwar1-94e9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENaHS9KplmT9-Zbwt4b_zRVgF-xskSGk',
    appId: '1:547078489764:ios:ec995d5a632b715af8c831',
    messagingSenderId: '547078489764',
    projectId: 'elsenwar1-94e9a',
    storageBucket: 'elsenwar1-94e9a.firebasestorage.app',
    iosBundleId: 'com.example.cleopatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDENaHS9KplmT9-Zbwt4b_zRVgF-xskSGk',
    appId: '1:547078489764:ios:ec995d5a632b715af8c831',
    messagingSenderId: '547078489764',
    projectId: 'elsenwar1-94e9a',
    storageBucket: 'elsenwar1-94e9a.firebasestorage.app',
    iosBundleId: 'com.example.cleopatra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAds0SsUHnSQB0xH4iv0cTjlpfa7GtNx-Y',
    appId: '1:547078489764:web:e357ac7d399847eaf8c831',
    messagingSenderId: '547078489764',
    projectId: 'elsenwar1-94e9a',
    authDomain: 'elsenwar1-94e9a.firebaseapp.com',
    storageBucket: 'elsenwar1-94e9a.firebasestorage.app',
    measurementId: 'G-YS40FQZSLQ',
  );
}
